
services: 
  backend:
    build:
      context: ./backend  # Path to the build context (where Dockerfile is located)
      dockerfile: Dockerfile            # Name of the Dockerfile
    image: cycleroom_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - influxdb
    volumes:
      - ./backend:/app
      - /run/dbus:/run/dbus:ro
    networks:
      - cycleroom_network
    privileged: true

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    networks:
      - cycleroom_network
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    env_file:
      - .env 
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    networks:
      - cycleroom_network
    volumes:
      - grafana_data:/var/lib/grafana

  flask-app:
    build:
      context: ./bike-dashboard # Path to the build context (where Dockerfile is located)
      dockerfile: Dockerfile            # Name of the Dockerfile
    ports:
      - "5000:5000"
    networks:
      - cycleroom_network
    volumes:
      - ./bike-dashboard:/app
networks:
  cycleroom_network:

volumes:
  influxdb_data:
  influxdb_config:
  grafana_data:
  
