version: '3.8'

services:
  backend:
    build: ./backend/
    container_name: backend
    volumes:
      - shared_data:/data
      - /var/run/dbus/:/var/run/dbus/:z
    restart: always
    privileged: true
    ports:
      - "8888:8888"
    networks:
      - cycle_network

volumes:
  shared_data:

networks:
  cycle_network:
    driver: bridge  