version: '3.8'

services: 
  backend:
    build:
      context: ./backend  # Path to the build context (where Dockerfile is located)
      dockerfile: Dockerfile            # Name of the Dockerfile
    image: cycleroom_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - influxdb
    volumes:
      - ./backend:/app
    networks:
      - cycleroom_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - cycleroom_network

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    networks:
      - cycleroom_network
    volumes:
      - influxdb_data:/var/lib/influxdb2

networks:
  cycleroom_network:

volumes:
  influxdb_data:
