
version: '3.8'

services:
  fastapi-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.fastapi
    container_name: fastapi-app
    ports:
      - "8000:8000"
    networks:
      - cycleroom-network
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - TIMESCALEDB_HOST=timescaledb
      - QUERY_INTERVAL=2

  visualization:
    build:
      context: ..
      dockerfile: docker/Dockerfile.visualization
    container_name: visualization
    depends_on:
      - fastapi-app
    networks:
      - cycleroom-network

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - cycleroom-network
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=cycleroom
      - DOCKER_INFLUXDB_INIT_BUCKET=metrics

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - "5432:5432"
    networks:
      - cycleroom-network
    environment:
      - POSTGRES_USER=timescale_user
      - POSTGRES_PASSWORD=timescale_password
      - POSTGRES_DB=timescale_db
    volumes:
      - timescale-data:/var/lib/postgresql/data

networks:
  cycleroom-network:
    driver: bridge

volumes:
  influxdb-data:
  timescale-data:
